version: 2.1
orbs:
  node: circleci/heroku@0.0.10.
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  deploy:
    executor:
      name: node/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "S1a:d4:d6:99:73:a0:8b:1f:28:bf:c5:5d:55:21:c2:7b"
      - run: pwd
workflows:
    build-and-test:
      jobs:
        - build-and-test
    heroku_deploy:
      jobs:
        - build
        - heroku/deploy-via-git:
            requires:
              - build-and-test
            filters:
              branches:
                only: sequential-branch-filter