version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build:
    docker:
      - image: cimg/node
    steps:
      - node/install-packages

workflows:
    build-and-test:
      jobs:
        - build
        - node/run
        - node/test
