version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build:
    docker:
        - image: cimg/node:18.9.0
    steps:
      - checkout

workflows:
    build:
      jobs:
        - build
        - node/test
