version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build:
    docker:
      - image: cimg/node:18.9.0
    steps:
      - checkout
      - run: node --version
      - node/install-packages

workflows:
    build-and-test:
      jobs:
        - node/run
        - node/test
