version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  deploy-job:
    executor:
      name: node/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "S1a:d4:d6:99:73:a0:8b:1f:28:bf:c5:5d:55:21:c2:7b"
      - run: rsync -va --delete / root@192.241.134.93:var/www/html

workflows:
    build-and-test:
      jobs:
        - build-and-test
        - deploy-job